matrix:
  include:
    - os: linux
      jdk: oraclejdk8
    - os: linux
      jdk: oraclejdk7
    - os: linux
      jdk: openjdk7
    - os: osx
      osx_image: xcode8.2
    - os: osx
      osx_image: xcode8.1
    - os: osx
      osx_image: xcode8
    - os: osx
      osx_image: xcode7.3
    - os: os
      osx_image: xcode6.4

language: java

script:
  - ./gradlew run

