language: java

os:
  - linux
  - osx

jdk:
  - oraclejdk7
  - openjdk7
  - oraclejdk8

before_install:
  - echo java -version
  - which jdk_switcher || alias jdk_switcher='echo disabled_jdk_switcher'

